[package]
name = "midi-m8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
m8-files = "0.1.0"
midi-msg = "0.4.0"
byteorder = "1.4.3"