[package]
name = "midi-m8-core"
version = "1.3.0"
edition = "2021"
description = "Core crate for midi-m8. M8 files to MIDI."
repository = "https://github.com/AlexCharlton/midi-m8"
license = "MIT"

[dependencies]
byteorder = "1.4.3"
m8-files = { workspace = true }
midi-msg = { workspace = true }
