# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
#
on: [push, pull_request]

name: CI

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Check
        run: cargo check

      - name: Test
        run: cargo test

      - name: fmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy -- -D warnings
