# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
#
on: [push, pull_request]

name: CI

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
          override: true
      - name: Setup | Cache
        uses: Swatinem/rust-cache@v2

      - name: Run | check
        run: cargo check

      - name: Run | test
        run: cargo test

      - name: Run | fmt
        run: cargo fmt --all -- --check

      - name: Run | clippy
        run: cargo clippy -- -D warnings
