# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
#
on: [push, pull_request]

name: CI

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
          override: true

      - uses: Swatinem/rust-cache@v2

      - run: cargo check 

      - run: cargo fmt --all -- --check

      - run: cargo clippy -- -D warnings
